### ISSUE TITLE
v0.3.1 has bug blocking import 

### ISSUE THREAD

**Issue by ryanrodemoyer** [j4w8n/htmlfy#7]
Getting this error in my app.

Import trace for requested module:
./node_modules/htmlfy/src/minify.js
./node_modules/htmlfy/src/exports/index.js
./app/page.tsx
 ⨯ ./node_modules/htmlfy/src/minify.js
Attempted import error: 'hasHtml' is not exported from './utils.js' (imported as 'hasHtml').

Next.js 14.2.14 w/ TypeScript 5

Solution was to downgrade to v0.3.0.

**Comment by ryanrodemoyer** [comment]
Otherwise, thank you for the nice package.

**Comment by j4w8n** [comment]
Thanks Ryan! I recently changed that function name and missed the import in that file. I just released a fix in v0.3.2!
