### ISSUE TITLE
Breaks inline script

### ISSUE THREAD

**Issue by toptensoftware** [j4w8n/htmlfy#8]
Thanks for this package, pretty keen to use it but it seems to break inline script:

eg: this script to load livereload ([from here](https://www.npmjs.com/package/livereload))

```js
<script>
    document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')
</script>
```

comes out like this and gives browser errors (newline inside single quote string):

```js
<script>document.write('
      <script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1">
      </' + 'script>')</script>
```

Also, I noticed css in `<style>`  elements gets flattened a single line.

Perhaps an option to just leave script and style content alone?

**Comment by j4w8n** [comment]
Thanks. I'll take a look and see what I can do.

**Comment by toptensoftware** [comment]
Thanks for looking into this.  Unfortunately, after some more testing it seems like there's a few issues - all related to whitespace handling.

Re the style element, before:

```html
<style>
body
{
    padding: 0;
    margin: 0;
}
</style>
```

After:

```html
<style>body{ padding: 0; margin: 0;}</style>
```

Expected: leave the content alone

It looks like it's stripping whitespace like it would for a normal HTML text nodes but css has its own weird set of whitespace rules so I'm concerned something could easily break here.

 `<pre>` tags don't work correctly:

Before:

```html
    <pre><code>// This is my code
Please()
{
    leave it alone
}
</code></pre>
```

After:

```html
<pre>
    <code>// This is my codePlease(){ leave it alone}</code>
</pre>
```

In this case it's dropping whitespace between words too (eg: "codePlease").  

Actually, it seems to be over aggressively removing new lines in other places too:

```html
<p>
This
is
a
paragraph
</p>
```

giving:

```html
<p>Thisisaparagraph</p>
```

Interestingly, `<textarea>` handles new lines differently but doesn't solve it as I expected:

```html
<textarea>This 
is 
a 
textarea

line1
line2
</textarea>
```

gives:

```html
<textarea>This &#13; is &#13; a &#13;textarea&#13;&#13;line1&#13;line2&#13;&#13; more</textarea>
```

This approach would also work for `<pre>`, maybe work for `<style>` (not sure, but personally I wouldn't like that). This approach would not work for `<script>`.

There's another issue with text area where it's incorrectly stripping leading and trailing blank lines

```html
<textarea>

text

</textarea>
```

gives:

```html
<textarea>text</textarea>
```

I believe it should strip the newline immediately after the opening `<textarea>` but keep the rest.  ie: it should give:

```html
<textarea>&#13;text&#13;&#13;</textarea>
```

**Comment by j4w8n** [comment]
Thank you for all of this feedback!

**Comment by toptensoftware** [comment]
No problem - I hope you can get it sorted.

**Comment by j4w8n** [comment]
@toptensoftware I believe most of this is now resolved in v0.4.0. In order to get this working easily, and without any breaking changes, I added an `ignore` configuration option.

```js
prettify(html_string, { ignore: [ 'script' ] })

// you'll need to supply both tag names for your nested example
prettify(html_string, { ignore: [ 'pre', 'code' ] })
```

The entities behavior for `textarea`s was in-place when I forked the code. I don't recall how much of the logic I might have tweaked, but I can go back and look. I'm still considering what to do here.

**Comment by j4w8n** [comment]
Looks as though I did remove the replacement of spaces with their respective entities. Also, the original author was trimming a leading new line with one or more spaces after the `<textarea>`, and one or more trailing spaces before the `</textarea>`. So, I suspect there's where I also added some removals of one or more leading new lines and whatnot.

**Comment by j4w8n** [comment]
> Another issue:
> 
> ```
> <p>This is<span style="background:orange"> orange </span>.</p>
> ```
> 
> gives:
> 
> ```
>  <p>This is
>       <span style="background:orange">orange</span>.</p>
> ```
> 
> (incorrectly removing the leading/trailing whitespace in the span).
> 
> Granted, this is a weird edge case, but it does change the rendered output.

I did not address this one yet.

**Comment by j4w8n** [comment]
What's your reasoning here?

> I believe it should strip the newline immediately after the opening <textarea> but keep the rest. ie: it should give:

```html
<textarea>

text

</textarea>
```
```html
<textarea>&#13;text&#13;&#13;</textarea>
```

**Comment by j4w8n** [comment]
> > Another issue:
> > ```
> > <p>This is<span style="background:orange"> orange </span>.</p>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gives:
> > ```
> >  <p>This is
> >       <span style="background:orange">orange</span>.</p>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (incorrectly removing the leading/trailing whitespace in the span).
> > Granted, this is a weird edge case, but it does change the rendered output.
> 
> I did not address this one yet.

Given the nature of `span`s, it might be worthy of automatic "ignoring".

**Comment by toptensoftware** [comment]
> ```
> <p>
> This
> is
> a
> paragraph
> </p>
> ```
> 
> This above giving the below, I'm not sure about either. Will need to look closer. Out of curiosity, what use-case is there to do the above?
> 
> `<p>Thisisaparagraph</p>`

I just noticed that it was removing new lines in another situation and thought I test with the above and that's what it gave.  The use case I guess is anything that's generating paragraphs with just line breaks between words.


> What's your reasoning here?
> 
> > I believe it should strip the newline immediately after the opening <textarea> but keep the rest. ie: it should give:
> 
> ```
> <textarea>
> 
> text
> 
> </textarea>
> ```
> 
> ```
> <textarea>&#13;text&#13;&#13;</textarea>
> ```

I think I mispoke - I was incorrectly referring to what the browser does, not what prettify should do.  I think you can ignore this except that it shouldn't trim leading/trailing new lines in a text area.

fwiw, thanks for looking into these issues but since reporting I've found a simpler solution - the html I was trying to prettify was being rendered by a server-side DOM in minified form.  I managed to write some code to inject newlines and indents in appropriate places and got close enough for what I needed.

It's a tricky problem to solve correctly.  In fact, given that you can adjust whitespace behaviour with css, it's probably not a problem that can be perfectly solved.  In any case all the best with it.
